#define CTI_HW_BOARD_NAME           "WIshioT ESP32 LoRa 915 MHz"
#define CTI_HW_FLASH_STORAGE_BYTES  (4 * 1024 * 1024)

#define CTI_BOARD_STATUS_LED_GPIO   25
#define CTI_BOARD_OLED_SDA_GPIO     4
#define CTI_BOARD_OLED_SCL_GPIO     15
#define CTI_BOARD_LORA_MOSI_GPIO   27
#define CTI_BOARD_LORA_MISO_GPIO   19
#define CTI_BOARD_LORA_SCK_GPIO     5
#define CTI_BOARD_LORA_CS_GPIO     18
#define CTI_BOARD_LORA_RESET_GPIO  14
#define CTI_BOARD_LORA_DIO0_GPIO   26
